create table if not exists public.players (
  id bigint generated by default as identity primary key,
  player_name text not null default 'Anonymous',
  phone_number text not null default '',
  age text default '',
  gender text default '',
  mbti text default '',
  playtime text default '',
  genres jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  player_id bigint references public.players(id) on delete set null,
  player_name text not null default 'Anonymous',
  played_at timestamptz not null default now(),
  deck jsonb not null,
  turn_sequence jsonb not null default '[]'::jsonb,
  player_board jsonb not null,
  ai_board jsonb not null,
  player_score integer not null,
  ai_score integer not null,
  duration_ms bigint not null default 0,
  result text not null
);

create table if not exists public.turns (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games(id) on delete cascade,
  turn_number integer not null,
  card_value integer not null,
  card_order integer not null default 1,
  deck_index integer not null default 0,
  player_slot integer not null,
  ai_slot integer not null,
  player_score_after integer not null default 0,
  ai_score_after integer not null default 0
);

alter table public.players enable row level security;
alter table public.games enable row level security;
alter table public.turns enable row level security;
